### ISSUE TITLE
Errors from dockerfile

### ISSUE THREAD

**Issue by JasonNielsen** [Yanall-Boutros/ParticleSHAI#1]
I have the following warnings and error when I try to build an image from the dockerfile:

After all new packages have been downloaded, I see this warning:
`debconf: delaying package configuration, since apt-utils is not installed`
but then everything continues fine for a while.

Then, when we uninstall pip and try to install python3-pip, I see
```
Step 6/13 : RUN python3 -m pip uninstall -y pip &&  apt install python3-pip --reinstall
 ---> Running in 6a6c1a64145e
Found existing installation: pip 20.1
Uninstalling pip-20.1:
  Successfully uninstalled pip-20.1

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```

Finally, there is a fatal error on the pip install, where I see
```
Step 7/13 : RUN pip install --user --upgrade pip
 ---> Running in 3802d9f4492f
/bin/sh: 1: pip: not found
The command '/bin/sh -c pip install --user --upgrade pip' returned a non-zero code: 127
```

As a result, the image does not compile.

**Comment by Yanall-Boutros** [comment]
Apologies, couldn't push  because I lost all my keys. Recompiling now.

That dockerfile is old, I will push the correct one. Only pip3 is needed, so removing the pip line "fixes" the issue.

**Comment by Yanall-Boutros** [comment]
Pushed to hub.docker, please try
`
sudo docker pull yboutros/particleshai`

There are changes in the tensorflow package however pythia is functional
